apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector
  labels:
    strimzi.io/cluster: postgres-connection
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  config:
    database.dbname: "postgres"
    database.hostname: "104.197.14.7"
    database.port: "32050"
    database.password: "admin123"
    database.server.name: "postgres"
    database.user: "postgres"
    plugin.name: "pgoutput"
    slot.name: kafka
    schema.whitelist: "public"
    table.whitelist: "public.demo"
    snapshot.mode: "always"
    # database.history.kafka.bootstrap.servers: "my-cluster-kafka-bootstrap:9092"
    # database.history.kafka.topic: "schema-changes.inventory"
  tasksMax: 1
